file = open('keyring.keys', 'x')
file.close()
file = open('algorithm.key', 'x')
file.close()
file = open('binaryhash.key', 'x')
file.close()
file = open('encryptor.key', 'x')
file.close()
file = open('encryptorbackup.key', 'x')
file.close()
file = open('salt.key', 'x')
file.close() 
file = open('saltbackup.key', 'x')
file.close()
file = open('hash.key', 'x')
file.close()
file = open('oldhash.key', 'x')
file.close() 
file = open('password.key', 'x')
file.close() 
file = open('oldpassword.key', 'x')
file.close() 
file = open('PPG.key', 'x')
file.close()
